[package]
name = "rand-file"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
fastrand = "2.3.0"
indicatif = "0.17.9"
rayon = "1.10.0"
tokio = { version = "1.43.0", features = ["full"] }
